% This code takes the data from GPM database (raw-data/gpm_data_.csv)
% and processes it in accordance with Global Rconomy Equilibrium model
% setup: US, EZ, CN and RC regions + all commodities
% Results are saved in results\dbcsv and results\dbmat for .csv and .mat
% outputs respectively.


clearvars; close all

addpath('codes');
addpath('raw-data');

% define countries codes and names
cclink = {...
...% real CC   bloc CC  real name
    'CN',      'CN',    'China'                     ;...
    'US',      'US',    'United States'             ;...    
    'AT',      'EZ',    'Austria'                   ;...
    'BE',      'EZ',    'Belgium'                   ;...
    'CY',      'EZ',    'Cyprus'                    ;...
    'EE',      'EZ',    'Estonia'                   ;...
    'FI',      'EZ',    'Finland'                   ;...
    'FR',      'EZ',    'France'                    ;...
    'DE',      'EZ',    'Germany'                   ;...
    'GR',      'EZ',    'Greece',                   ;...
    'IE',      'EZ',    'Ireland'                   ;...
    'IT',      'EZ',    'Italy'                     ;...
    'LV',      'EZ',    'Latvia'                    ;...
    'LT',      'EZ',    'Lithuania'                 ;...
    'LU',      'EZ',    'Luxembourg'                ;...
    'MT',      'EZ',    'Malta'                     ;...
    'NL',      'EZ',    'Netherlands'               ;...
    'PT',      'EZ',    'Portugal'                  ;...
    'SK',      'EZ',    'Slovak Republic'           ;...
    'SI',      'EZ',    'Slovenia'                  ;...
    'ES',      'EZ',    'Spain'                     ;...
    'IN',      'RC',    'India'                     ;...
    'JP',      'RC',    'Japan'                     ;...
    'RU',      'RC',    'Russia'                    ;...
    'BR',      'RC',    'Brazil'                    ;...
    'ID',      'RC',    'Indonesia'                 ;...
    'GB',      'RC',    'United Kingdom'            ;...
    'MX',      'RC',    'Mexico'                    ;...
    'TR',      'RC',    'Turkey'                    ;...
    'KR',      'RC',    'Korea'                     ;...
    'ZA',      'RC',    'South Africa'              ;...    
    'HK',      'RC',    'Hong Kong SAR'             ;...
    'TW',      'RC',    'Taiwan Province of China'  ;...
    'MY',      'RC',    'Malaysia'                  ;...
    'PH',      'RC',    'Philippines'               ;...
    'TH',      'RC',    'Thailand'                  ;...
    'VN',      'RC',    'Vietnam'                   ;...
    'CO',      'RC',    'Colombia'                  ;...
    'PE',      'RC',    'Peru'                      ;...
    'NZ',      'RC',    'New Zealand'               ;...
    'CA',      'RC',    'Canada'                    ;...
    'AU',      'RC',    'Australia'                 ;...
    'NO',      'RC',    'Norway'                    ;...
    'CZ',      'RC',    'Czech Republic'            ;...
    'DK',      'RC',    'Denmark'                   ;...    
    'IL',      'RC',    'Israel'                    ;...    
    'SG',      'RC',    'Singapore'                 ;...
    'SE',      'RC',    'Sweden'                    ;...
    'CH',      'RC',    'Switzerland'               ;...
    'PL',      'RC',    'Poland'                    ;...
    'CL',      'RC',    'Chile'                     ;...
};

cclink_tab = cell2table(cclink,'Rownames',cclink(:,1),...
    'VariableNames',{'cc', 'block', 'cc name'});
% get country codes and trade partners list
cclist = unique(cclink(:,2));
 
% commodities
comvars = {'OIL','FOOD','GOLD','COAL','COBALT','COPPER', ...
             'IRON','COCOA'};
         
disp('Loading the data...')
histDataFile = fullfile('raw-data','gpm_data_.csv');
dobs = databank.fromCSV(histDataFile);

% define key dates
firstHist = qq(2004,1);

% create attributes which will be used at next steps
attribs = struct('cclink',    {cclink},...
                 'comvars',   {comvars},...
                 'firstHist', firstHist);

% aggregate data to account for links between countries 
md = gpm_model_data(dobs, attribs);

% special treatment of RC inflation and GDP at the end of the sample due to
% missing data for many countries (algorithm calculates variables even if some countries data are missing).
% now done automatically in gpm_model_data, but can be forced by user
% md.OBS_L_GDP_RC(qq(2020,1)) = NaN;


% save data
if ~exist(fullfile('results','dbmat'),'dir')
    mkdir(fullfile('results','dbmat'));
end
save(fullfile('results','dbmat','gpm_data.mat'),'md');
if ~exist(fullfile('results','dbcsv'),'dir')
    mkdir(fullfile('results','dbcsv'));
end
databank.toCSV(md,fullfile('results','dbcsv','gpm_data.csv'),...
                   'dateformat','YYYYFP');

disp('Done succesfully!');         