function [smc, s] = disinflation(m)

T = 20;

d = steadydb(m, 1:T);

m.ss_roc_pch = m.ss_roc_pch - 0.01;

m = steady( ...
    m ...
    , "fixLevel", ["y", "nn", "pch", "ss_dg_to_ngdp"] ...
    , "blocks", false ...
);

checkSteady(m);
m = solve(m);

s = simulate( ...
    m, d, 1:T ...
    , "prependInput", true ...
    , "method", "stacked" ...
);

smc = databank.minusControl(m, s, d);

end%
