
close all
clear

history = readtable( ...
    "+feb2024/WPP2022_Estimates.csv" ...
    , NumHeaderLines=0 ...
    , TextType="string" ...
    , VariableNamingRule="preserve" ...
);

projection = readtable( ...
    "+feb2024/WPP2022_Medium_Projection.csv" ...
    , NumHeaderLines=0 ...
    , TextType="string" ...
    , VariableNamingRule="preserve" ...
);

historyDb = databankFromTable(history);
projectionDb = databankFromTable(projection);
wpp = databank.merge("vertcat", historyDb, projectionDb);

wpp.startHist = yy(1950);
wpp.endHist = yy(2021);
wpp.startProj = yy(2022);
wpp.endProj = yy(2100);

disp(wpp)

save +feb2024/mat/wpp2022_data.mat wpp


function db = databankFromTable(table)

    inxWorld = table.("Location code") == 900;

    ea = struct( ...
        "at", 040, ...
        "be", 056, ...
        "cy", 196, ...
        "ee", 233, ...
        "fi", 246, ...
        "fr", 250, ...
        "de", 276, ...
        "gr", 300, ...
        "ie", 372, ...
        "it", 380, ...
        "lv", 428, ...
        "lt", 440, ...
        "lu", 442, ...
        "mt", 470, ...
        "nl", 528, ...
        "pt", 620, ...
        "sk", 703, ...
        "si", 705, ...
        "es", 724, ...
        "hr", 191 ...
    );

    db = struct();
    db.ea_n14 = 0;
    db.ea_nn = 0;
    db.ea_nw = 0;
    db.ea_n65 = 0;
    for n = databank.fieldNames(ea)
        code = ea.(n);
        inx = table.("Location code") == code;
        year = yy(table.Year(inx));
        n14 = table.("0-14")(inx);
        nw = table.("15-64")(inx);
        nn = table.("Total")(inx);
        n65 = table.("65+")(inx);
        db.(n+"_n14") = Series(year, n14);
        db.(n+"_nn") = Series(year, nn);
        db.(n+"_nw") = Series(year, nw);
        db.(n+"_n65") = Series(year, n65);
        db.(n+"_nw_to_nn") = db.(n+"_nw") / db.(n+"_nn");
        db.ea_nn = db.ea_nn + db.(n+"_nn");
        db.ea_n14 = db.ea_n14 + db.(n+"_n14");
        db.ea_nw = db.ea_nw + db.(n+"_nw");
        db.ea_n65 = db.ea_n65 + db.(n+"_n65");
    end
    db.ea_nw_to_nn = db.ea_nw / db.ea_nn;

    regions = struct( ...
        "gg", 900, ...
        "cn", 156, ...
        "us", 840 ...
    );

    for n = databank.fieldNames(regions)
        inx = table.("Location code") == regions.(n);
        db.(n+"_n14") = Series(yy(table.Year(inx)), table.("0-14")(inx));
        db.(n+"_nn") = Series(yy(table.Year(inx)), table.("Total")(inx));
        db.(n+"_nw") = Series(yy(table.Year(inx)), table.("15-64")(inx));
        db.(n+"_n65") = Series(yy(table.Year(inx)), table.("65+")(inx));
        db.(n+"_nw_to_nn") = db.(n+"_nw") / db.(n+"_nn");
    end

    db.rw_n14 = db.gg_n14 - db.cn_n14 - db.us_n14 - db.ea_n14;
    db.rw_nn = db.gg_nn - db.cn_nn - db.us_nn - db.ea_nn;
    db.rw_nw = db.gg_nw - db.cn_nw - db.us_nw - db.ea_nw;
    db.rw_n65 = db.gg_n65 - db.cn_n65 - db.us_n65 - db.ea_n65;
    db.rw_nw_to_nn = db.rw_nw / db.rw_nn;

end%

