function [s, smc] = areaProductivityImprovements(m, area)

T = 20;

d = steadydb(m, 1:T);

m.(area+"_ss_ar") = m.(area+"_ss_ar") * 1.10;

m = steady( ...
    m ...
    , "fixLevel", ["gg_a", "gg_nt", "us_pch", "ea_pch", "rw_pch"] ...
    , "blocks", false ...
);

checkSteady(m);
m = solve(m);

p = Plan.forModel(m, 1:T);
p = swap(p, 1:3, [area+"_ar", area+"_shk_ar"]);

s = simulate( ...
    m, d, 1:T ...
    , "prependInput", true ...
    , "method", "stacked" ...
    , "blocks", false ...
    , "plan", p ...
);

smc = databank.minusControl(m, s, d);

end%

