classdef trade_matrix

  properties (Constant)
    COUNTRY_NAMES_CODES = {...
    % Country Name DOTS                     country name ISO-3166                     2-letter ISO-3166   3-letter ISO-3166
    'Afghanistan__Islamic_Republic_of'     ,'Afghanistan',                                          'AF', 'AFG';...
    'Albania'                              ,'Albania',                                              'AL', 'ALB';...
    'Algeria'                              ,'Algeria',                                              'DZ', 'DZA';...
    'Angola'                               ,'Angola',                                               'AO', 'AGO';...
    'Argentina'                            ,'Argentina',                                            'AR', 'ARG';...
    'Armenia__Republic_of'                 ,'Armenia',                                              'AM', 'ARM';...
    'Australia'                            ,'Australia',                                            'AU', 'AUS';...
    'Austria'                              ,'Austria',                                              'AT', 'AUT';...
    'Azerbaijan__Republic_of'              ,'Azerbaijan',                                           'AZ', 'AZE';...
    'Bahamas__The'                         ,'Bahamas',                                              'BS', 'BHS';...
    'Bahrain__Kingdom_of'                  ,'Bahrain',                                              'BH', 'BHR';...
    'Bangladesh'                           ,'Bangladesh',                                           'BD', 'BGD';...
    'Barbados'                             ,'Barbados',                                             'BB', 'BRB';...
    'Belarus'                              ,'Belarus',                                              'BY', 'BLR';...
    'Belgium'                              ,'Belgium',                                              'BE', 'BEL';...
    'Belize'                               ,'Belize',                                               'BZ', 'BLZ';...
    'Benin'                                ,'Benin',                                                'BJ', 'BEN';...
    'Bolivia'                              ,'Bolivia (Plurinational State of)',                     'BO', 'BOL';...
    'Bosnia_and_Herzegovina'               ,'Bosnia and Herzegovina',                               'BA', 'BIH';...
    'Botswana'                             ,'Botswana',                                             'BW', 'BWA';...
    'Brazil'                               ,'Brazil',                                               'BR', 'BRA';...
    'Brunei_Darussalam'                    ,'Brunei Darussalam',                                    'BN', 'BRN';...
    'Bulgaria'                             ,'Bulgaria',                                             'BG', 'BGR';...
    'Burkina_Faso'                         ,'Burkina Faso',                                         'BF', 'BFA';...
    'Burundi'                              ,'Burundi',                                              'BI', 'BDI';...
    'Cape_Verde'                           ,'Cabo Verde',                                           'CV', 'CPV';...
    'Cambodia'                             ,'Cambodia',                                             'KH', 'KHM';...
    'Cameroon'                             ,'Cameroon',                                             'CM', 'CMR';...
    'Canada'                               ,'Canada',                                               'CA', 'CAN';...
    'Central_African_Republic'             ,'Central African Republic',                             'CF', 'CAF';...
    'Chad'                                 ,'Chad',                                                 'TD', 'TCD';...
    'Chile'                                ,'Chile',                                                'CL', 'CHL';...
    'China__P_R___Hong_Kong'               ,'Hong Kong',                                            'HK', 'HKG';...
    'China__P_R___Macao'                   ,'Macao',                                                'MO', 'MAC';...
    'China__P_R___Mainland'                ,'China',                                                'CN', 'CHN';...
    'Taiwan'                               ,'Taiwan, Province of China[a]',                         'TW', 'TWN';...
    'Colombia'                             ,'Colombia',                                             'CO', 'COL';...
    'Comoros'                              ,'Comoros',                                              'KM', 'COM';...
    'Congo__Republic_of'                   ,'Congo',                                                'CG', 'COG';...
    'Congo__Democratic_Republic_of'        ,'Congo (Democratic Republic of the)',                   'CD', 'COD';...
    'Costa_Rica'                           ,'Costa Rica',                                           'CR', 'CRI';...
    'Cote_d_Ivoire'                        ,'Cote d_Ivoire',                                        'CI', 'CIV';...
    'Croatia'                              ,'Croatia',                                              'HR', 'HRV';...
    'Cuba'                                 ,'Cuba',                                                 'CU', 'CUB';...
    'Cyprus'                               ,'Cyprus',                                               'CY', 'CYP';...
    'Czech_Republic'                       ,'Czechia',                                              'CZ', 'CZE';...
    'Denmark'                              ,'Denmark',                                              'DK', 'DNK';...
    'Djibouti'                             ,'Djibouti',                                             'DJ', 'DJI';...
    'Dominica'                             ,'Dominica',                                             'DM', 'DMA';...
    'Dominican_Republic'                   ,'Dominican Republic',                                   'DO', 'DOM';...
    'Ecuador'                              ,'Ecuador',                                              'EC', 'ECU';...
    'Egypt'                                ,'Egypt',                                                'EG', 'EGY';...
    'El_Salvador'                          ,'El Salvador',                                          'SV', 'SLV';...
    'Equatorial_Guinea'                    ,'Equatorial Guinea',                                    'GQ', 'GNQ';...
    'Estonia'                              ,'Estonia',                                              'EE', 'EST';...
    'Ethiopia'                             ,'Ethiopia',                                             'ET', 'ETH';...
    'Fiji'                                 ,'Fiji',                                                 'FJ', 'FJI';...
    'Finland'                              ,'Finland',                                              'FI', 'FIN';...
    'France'                               ,'France',                                               'FR', 'FRA';...
    'Gabon'                                ,'Gabon',                                                'GA', 'GAB';...
    'Gambia__The'                          ,'Gambia',                                               'GM', 'GMB';...
    'Georgia'                              ,'Georgia',                                              'GE', 'GEO';...
    'Germany'                              ,'Germany',                                              'DE', 'DEU';...
    'Ghana'                                ,'Ghana',                                                'GH', 'GHA';...
    'Greece'                               ,'Greece',                                               'GR', 'GRC';...
    'Grenada'                              ,'Grenada',                                              'GD', 'GRD';...
    'Guatemala'                            ,'Guatemala',                                            'GT', 'GTM';...
    'Guinea'                               ,'Guinea',                                               'GN', 'GIN';...
    'Guinea_Bissau'                        ,'Guinea-Bissau',                                        'GW', 'GNB';...
    'Guyana'                               ,'Guyana',                                               'GY', 'GUY';...
    'Haiti'                                ,'Haiti',                                                'HT', 'HTI';...
    'Honduras'                             ,'Honduras',                                             'HN', 'HND';...
    'Hungary'                              ,'Hungary',                                              'HU', 'HUN';...
    'Iceland'                              ,'Iceland',                                              'IS', 'ISL';...
    'India'                                ,'India',                                                'IN', 'IND';...
    'Indonesia'                            ,'Indonesia',                                            'ID', 'IDN';...
    'Iran__Islamic_Republic_of'            ,'Iran (Islamic Republic of)',                           'IR', 'IRN';...
    'Iraq'                                 ,'Iraq',                                                 'IQ', 'IRQ';...
    'Ireland'                              ,'Ireland',                                              'IE', 'IRL';...
    'Israel'                               ,'Israel',                                               'IL', 'ISR';...
    'Italy'                                ,'Italy',                                                'IT', 'ITA';...
    'Jamaica'                              ,'Jamaica',                                              'JM', 'JAM';...
    'Japan'                                ,'Japan',                                                'JP', 'JPN';...
    'Jordan'                               ,'Jordan',                                               'JO', 'JOR';...
    'Kazakhstan'                           ,'Kazakhstan',                                           'KZ', 'KAZ';...
    'Kenya'                                ,'Kenya',                                                'KE', 'KEN';...
    'Korea__Democratic_People_s_Rep__of'   ,'Korea (Democratic People_s Republic of)',              'KP', 'PRK';...
    'Korea__Republic_of'                   ,'Korea (Republic of)',                                  'KR', 'KOR';...
    'Kuwait'                               ,'Kuwait',                                               'KW', 'KWT';...
    'Kyrgyz_Republic'                      ,'Kyrgyzstan',                                           'KG', 'KGZ';...
    'Lao_People_s_Democratic_Republic'     ,'Lao People_s Democratic Republic',                     'LA', 'LAO';...
    'Latvia'                               ,'Latvia',                                               'LV', 'LVA';...
    'Lebanon'                              ,'Lebanon',                                              'LB', 'LBN';...
    'Liberia'                              ,'Liberia',                                              'LR', 'LBR';...
    'Libya'                                ,'Libya',                                                'LY', 'LBY';...
    'Lithuania'                            ,'Lithuania',                                            'LT', 'LTU';...
    'Luxembourg'                           ,'Luxembourg',                                           'LU', 'LUX';...
    'Macedonia__FYR'                       ,'Macedonia (the former Yugoslav Republic of)',          'MK', 'MKD';...
    'Madagascar'                           ,'Madagascar',                                           'MG', 'MDG';...
    'Malawi'                               ,'Malawi',                                               'MW', 'MWI';...
    'Malaysia'                             ,'Malaysia',                                             'MY', 'MYS';...
    'Maldives'                             ,'Maldives',                                             'MV', 'MDV';...
    'Mali'                                 ,'Mali',                                                 'ML', 'MLI';...
    'Malta'                                ,'Malta',                                                'MT', 'MLT';...
    'Mauritania'                           ,'Mauritania',                                           'MR', 'MRT';...
    'Mauritius'                            ,'Mauritius',                                            'MU', 'MUS';...
    'Mexico'                               ,'Mexico',                                               'MX', 'MEX';...
    'Moldova'                              ,'Moldova (Republic of)',                                'MD', 'MDA';...
    'Mongolia'                             ,'Mongolia',                                             'MN', 'MNG';...
    'Montenegro'                           ,'Montenegro',                                           'ME', 'MNE';...
    'Morocco'                              ,'Morocco',                                              'MA', 'MAR';...
    'Mozambique'                           ,'Mozambique',                                           'MZ', 'MOZ';...
    'Myanmar'                              ,'Myanmar',                                              'MM', 'MMR';...
    'Nepal'                                ,'Nepal',                                                'NP', 'NPL';...
    'Netherlands'                          ,'Netherlands',                                          'NL', 'NLD';...
    'New_Zealand'                          ,'New Zealand',                                          'NZ', 'NZL';...
    'Nicaragua'                            ,'Nicaragua',                                            'NI', 'NIC';...
    'Niger'                                ,'Niger',                                                'NE', 'NER';...
    'Nigeria'                              ,'Nigeria',                                              'NG', 'NGA';...
    'Norway'                               ,'Norway',                                               'NO', 'NOR';...
    'Oman'                                 ,'Oman',                                                 'OM', 'OMN';...
    'Pakistan'                             ,'Pakistan',                                             'PK', 'PAK';...
    'Panama'                               ,'Panama',                                               'PA', 'PAN';...
    'Papua_New_Guinea'                     ,'Papua New Guinea',                                     'PG', 'PNG';...
    'Paraguay'                             ,'Paraguay',                                             'PY', 'PRY';...
    'Peru'                                 ,'Peru',                                                 'PE', 'PER';...
    'Philippines'                          ,'Philippines',                                          'PH', 'PHL';...
    'Poland'                               ,'Poland',                                               'PL', 'POL';...
    'Portugal'                             ,'Portugal',                                             'PT', 'PRT';...
    'Qatar'                                ,'Qatar',                                                'QA', 'QAT';...
    'Romania'                              ,'Romania',                                              'RO', 'ROU';...
    'Russian_Federation'                   ,'Russian Federation',                                   'RU', 'RUS';...
    'Rwanda'                               ,'Rwanda',                                               'RW', 'RWA';...
    'Samoa'                                ,'Samoa',                                                'WS', 'WSM';...
    'Sao_Tome_and_Principe'                ,'Sao Tome and Principe',                                'ST', 'STP';...
    'Saudi_Arabia'                         ,'Saudi Arabia',                                         'SA', 'SAU';...
    'Senegal'                              ,'Senegal',                                              'SN', 'SEN';...
    'Serbia__Republic_of'                  ,'Serbia',                                               'RS', 'SRB';...
    'Seychelles'                           ,'Seychelles',                                           'SC', 'SYC';...
    'Sierra_Leone'                         ,'Sierra Leone',                                         'SL', 'SLE';...
    'Singapore'                            ,'Singapore',                                            'SG', 'SGP';...
    'Slovak_Republic'                      ,'Slovakia',                                             'SK', 'SVK';...
    'Slovenia'                             ,'Slovenia',                                             'SI', 'SVN';...
    'Solomon_Islands'                      ,'Solomon Islands',                                      'SB', 'SLB';...
    'Somalia'                              ,'Somalia',                                              'SO', 'SOM';...
    'South_Africa'                         ,'South Africa',                                         'ZA', 'ZAF';...
    'Spain'                                ,'Spain',                                                'ES', 'ESP';...
    'Sri_Lanka'                            ,'Sri Lanka',                                            'LK', 'LKA';...
    'St__Kitts_and_Nevis'                  ,'Saint Kitts and Nevis',                                'KN', 'KNA';...
    'St__Lucia'                            ,'Saint Lucia',                                          'LC', 'LCA';...
    'St__Vincent_and_the_Grenadines'       ,'Saint Vincent and the Grenadines',                     'VC', 'VCT';...
    'Sudan'                                ,'Sudan',                                                'SD', 'SDN';...
    'Suriname'                             ,'Suriname',                                             'SR', 'SUR';...
    'Sweden'                               ,'Sweden',                                               'SE', 'SWE';...
    'Switzerland'                          ,'Switzerland',                                          'CH', 'CHE';...
    'Syrian_Arab_Republic'                 ,'Syrian Arab Republic',                                 'SY', 'SYR';...
    'Tajikistan'                           ,'Tajikistan',                                           'TJ', 'TJK';...
    'Tanzania'                             ,'Tanzania, United Republic of',                         'TZ', 'TZA';...
    'Thailand'                             ,'Thailand',                                             'TH', 'THA';...
    'Togo'                                 ,'Togo',                                                 'TG', 'TGO';...
    'Tonga'                                ,'Tonga',                                                'TO', 'TON';...
    'Trinidad_and_Tobago'                  ,'Trinidad and Tobago',                                  'TT', 'TTO';...
    'Tunisia'                              ,'Tunisia',                                              'TN', 'TUN';...
    'Turkey'                               ,'Turkey',                                               'TR', 'TUR';...
    'Turkmenistan'                         ,'Turkmenistan',                                         'TM', 'TKM';...
    'Uganda'                               ,'Uganda',                                               'UG', 'UGA';...
    'Ukraine'                              ,'Ukraine',                                              'UA', 'UKR';...
    'United_Arab_Emirates'                 ,'United Arab Emirates',                                 'AE', 'ARE';...
    'United_Kingdom'                       ,'United Kingdom of Great Britain and Northern Ireland', 'GB', 'GBR';...
    'United_States'                        ,'United States of America',                             'US', 'USA';...
    'Uruguay'                              ,'Uruguay',                                              'UY', 'URY';...
    'Uzbekistan'                           ,'Uzbekistan',                                           'UZ', 'UZB';...
    'Vanuatu'                              ,'Vanuatu',                                              'VU', 'VUT';...
    'Venezuela__Republica_Bolivariana_de'  ,'Venezuela (Bolivarian Republic of)',                   'VE', 'VEN';...
    'Vietnam'                              ,'Viet Nam',                                             'VN', 'VNM';...
    'Yemen__Republic_of'                   ,'Yemen',                                                'YE', 'YEM';...
    'Zambia'                               ,'Zambia',                                               'ZM', 'ZMB';...
    'Zimbabwe'                             ,'Zimbabwe',                                             'ZW', 'ZWE';...
                   };
    
  end

  properties (SetAccess = protected)
    % List of countries in the matrix. These countries do not need to be
    % countries from COUNTRY_NAMES_CODES, they can be their aggregations,
    % etc. By convention, these strings will be 2-letter code, for
    % existing countries it is the third column in COUNTRY_NAMES_CODES
    countries = {};
    
    % Trade matrix: rows are origins of the trade, columns are
    % destinations. matrix(i,j) is export from countries{i} to
    % countries{j}. All items are trade volumes in the same unit
    tmatrix = [];
  end
  
  methods

    % construct from the IMF DOTS database
    %
    % fname    string for the xls filename of the DOTs database; if empty
    %          then we use ../data/dots_trade_export_2017.xls file
    % year     string for the name of sheet in the DOTs database
    function self = trade_matrix(fname, year)
      %- get default fname if empty
      if isempty(fname)
        fname = trade_matrix.get_default_fname();
      end
      %- read the file and get the data
      [num, txt, ~] = xlsread(fname, year, '', 'basic');
      data = num;
      data(isnan(data)) = 0.0;
      %- get intersection of rows and columns, forget about others
      row_countries = txt(2:end,1);
      col_countries = txt(1,2:end);
      [rc_countries, irow, jcol] = ...
          intersect(row_countries, col_countries);
      data = data(irow, jcol);
      %- now find rc_countries and restrict them only on self.COUNTRY_NAMES_CODES
      ctrs = {};
      for i = 1:numel(rc_countries)
        ctrs{end+1} = trade_matrix.convert_name(rc_countries{i});
      end
      [~, iisel, jjsel] = intersect(self.COUNTRY_NAMES_CODES(:,1)',ctrs);
      %- and set object data
      self.countries = self.COUNTRY_NAMES_CODES(iisel,3)';
      self.tmatrix = data(jjsel, jjsel);
      %- add taiwan
      [self.countries, self.tmatrix] = ...
          trade_matrix.add_taiwan(self.countries, self.tmatrix);
    end
    
    % restrict the trade matrix only to the countries given in the list;
    % function takes all trade from countries in the list to outside
    % countries and back, it ignores the trade ending in the outside
    % countries, the trade volumes are then upscaled to offset for the
    % lost trade
    %
    % lst    cell array of countries, should be a subset of self.countries
    % method 1=scaling by scalar,2=scaling by the same vectors for rows
    %        and columns 
    function self = restrict(self, lst, method)
      lst = unique(sort(lst));
      [~, ~, isel] = intersect(lst, self.countries);
      if length(isel) < length(lst)
        error(['Selected countries for restriction are not a subset of the ' ...
               'countries in the trade matrix']);
      end
      
      % prepare for restricting
      n = length(self.countries);
      ixsel = setdiff([1:n], isel);
      ns = length(isel);
      X = sum(self.tmatrix,2);
      M = sum(self.tmatrix,1)';
      smatrix = diag(X)\self.tmatrix;
      wx = zeros(n, ns);
      wx(ixsel,:) = smatrix(ixsel, isel); % exports from xsel to sel
      wx(isel,:) = eye(ns, ns);
      % distribute exports from sel to xsel to sel
      self.tmatrix = self.tmatrix(isel,:)*wx;
      self.tmatrix(1:ns+1:end) = 0; % zeros to diagonal
      % scale up the resulting matrix to orginal volumne of flows
      if method == 1
        self.tmatrix = trade_matrix.scale_matrix_1(self.tmatrix, X(isel), M(isel));
      else
        f = sum(X(isel)+M(isel))/2;
        A = trade_matrix.scale_matrix_2(self.tmatrix/f, X(isel)/f, M(isel)/f);
        self.tmatrix = A*f;
      end
      % restrict the countries
      self.countries = self.countries(isel);
    end
    
    % aggregate trade matrix
    %
    % rel is a cell array of new codes of the same size of the counries
    % in the current trade matrix rel{i} is a new country bloc to which
    % the i-th country belongs
    function self = aggregate(self, rel)
      [tmp, ii] = sort(rel);
      iinv(ii) = [1:length(ii)]';
      [cc, ~, ic] = unique(tmp);
      jj = ic(iinv); % now it holds that rel{i}=cc{jj(i)} for all i
  
      % construct matrix Z making the aggregations
      Z = zeros(length(cc), length(jj));
      for i=1:length(jj)
        Z(jj(i),i) = 1;
      end
  
      % aggregate the data
      self.tmatrix = Z*self.tmatrix*Z';
      % zeros to diagonal to kill intra-bloc trade
      n = size(self.tmatrix,1);
      self.tmatrix(1:n+1:end) = 0;
      % and return new vector of countries
      self.countries = cc;
    end
  end
  
  methods (Static)
    % convert name found in DOTs database so that it contains only nice characters
    function str = convert_name(str)
      str = regexprep(str,'^\s+','');
      str = regexprep(str,'\s+$','');
      str = regexprep(str,'\W','_');  
      str = strrep(str,'ú','u');
      str = strrep(str,'ô','o');
      str = strrep(str, '''', '_');
    end
    
    % scale matrix A so that it replicates exports X and imports M with
    % one scaling factors scalar xi
    function [B, xi] = scale_matrix_1(A, X, M)
      xm = [X; M];
      a = [sum(A, 2); sum(A, 1)'];
      xi = a\xm;
      B = xi*A;
    end
    
    % scale matrix A so that it replicates exports X and imports M with
    % vector scaling xi: B = diag(xi)*A*diag(xi) so that
    % rx(xi,X)=sum(B,2)-X and rm(xi,M)=sum(B,1)-M are minimized
    function [B, xi] = scale_matrix_2(A, X, M)
      n = size(A, 1);
      [~,ksi] = trade_matrix.scale_matrix_1(A,X,M);
      xi0 = sqrt(ksi)*ones(n, 1);
      H0 = eye(n, n);
      [fh,xh,gh,H,itct,fcount,retcodeh] ...
          = csminwel('trade_matrix.csminwel_sc2_objective_value',xi0,H0, ...
                     'trade_matrix.csminwel_sc2_objective_gradient',...
                     1e-09,100,3,A,X,M);
      xi = xh;
      B = diag(xi)*A*diag(xi);
    end

    % Attempts to do the same scale_matrix_3 with Newton method, works
    % little worse than csminwel
    function [B, xi] = scale_matrix_3(A, X, M)
      n = size(A, 1);
      rx = @(xi) [xi.*(A*xi)-X];
      rm = @(xi) [xi.*(A'*xi)-M];
      Jx = @(xi) [diag(A*xi) + A*diag(xi)];
      Jm = @(xi) [diag(A'*xi) + A'*diag(xi)];
      [~,ksi] = trade_matrix.scale_matrix_1(A,X,M);
      xi = sqrt(ksi)*ones(n, 1);
      res = [rx(xi); rm(xi)];
      i = 0;
      converged = false;
      while ~converged && i < 1000
        Jxi = [Jx(xi); Jm(xi)];
        g = Jxi'*res;
        rxm = rx(xi)+rm(xi);
        H = Jxi'*Jxi + diag(rxm)*A + A'*diag(rxm);
        dxi = H\g;
        obj = @(alpha) sum(rx(xi-alpha*dxi).^2) + sum(rm(xi-alpha*dxi).^2);
        alpha = trade_matrix.line_search(obj);
        xi = xi - alpha*dxi;
        res = [rx(xi); rm(xi)];
        i = i + 1;
        converged = norm(dxi) < 1e-10;
        disp(num2str([i, 0.5*sum(res.^2), norm(dxi), alpha]));
      end
      B = diag(xi)*A*diag(xi);
    end
    
    % simple line search between 0 and 1
    function alpha = line_search(f)
      tol = 1e-5;
      maxi = 30;
      i = 0;
      a = 0;
      b = 1;
      fa = f(a);
      fb = f(b);
      phi = (1+sqrt(5))/2;
      c = b - (b-a)/phi;
      d = a + (b-a)/phi;
      fc = f(c);
      fd = f(d);
      while abs(c-a) > tol*(abs(b)+abs(d)) && i < maxi 
        if fc < fd
          b = d;
          fb = fd;
          d = c;
          fd = fc;
          c = b + (a-b)/phi;
          fc = f(c);
        else
          a = c;
          fa = fc;
          c = d;
          fc = fd;
          d = a + (b-a)/phi;
          fd = f(d);
        end
        i = i + 1;
      end
      tmp = [fa,fb,fc,fd];
      ii = find(tmp==min(tmp));
      tmp = [a,b,c,d];
      alpha = tmp(ii(1));
    end
    
    % objective function for scaling_2 problem
    function f = sc2_objective_value(xi, A, X, M)
      resx = xi.*(A*xi)-X;
      resm = xi.*(A'*xi)-M;
      f = 0.5*sum([resx;resm].^2);
    end
    
    % gradient of objective function for balancing problem
    function g = sc2_objective_gradient(xi, A, X, M)
      n = length(xi);
      resx = xi.*(A*xi)-X;
      resm = xi.*(A'*xi)-M;
      Jx = diag(A*xi) + A*diag(xi);
      Jm = diag(A'*xi) + A'*diag(xi);
      g = Jx'*resx + Jm'*resm;
    end
  
    % csminwel wrapper for objective function of the balancing problem
    function [f, cost_flag] = csminwel_sc2_objective_value(xi, A, X, M)
      f = trade_matrix.sc2_objective_value(xi, A, X, M);
      cost_flag = 1;
    end
    
    % csminwel wrapper for objective function gradient of the balancing problem
    function [g, badg] = csminwel_sc2_objective_gradient(xi, A, X, M)
      g = trade_matrix.sc2_objective_gradient(xi, A, X, M);
      badg = false;
    end
  
    % return structure mapping iso 2-letter codes to iso 3-letter codes
    function s = iso_two2three()
      cc = trade_matrix.COUNTRY_NAMES_CODES(:,[3,4])';
      s = struct(cc{:});
    end

    % return structure mapping iso 3-letter codes to iso 2-letter codes 
    function s = iso_three2two()
      cc = trade_matrix.COUNTRY_NAMES_CODES(:,[4,3])';
      s = struct(cc{:});
    end
  end


  
  methods (Static, Access=private)
    % add taiwan
    function [countries, tmatrix] = add_taiwan(countries, tmatrix)
      s_cn = 21291.766; % GDPPPP 2016 WEO April 2017
      s_tw = 1132.1420; % GDPPPP 2016 WEO April 2017
      tw2cn = 152.0e9; % source wiki, 2014
      cn2tw = 45.0e9; % source wiki, 2014
      w_cn = s_cn/(s_cn+s_tw);
      w_tw = s_tw/(s_cn+s_tw);
      icn = strmatch('CN', countries, 'exact');
      xcn = tmatrix(icn, :);
      mcn = tmatrix(:, icn);
      tmatrix(icn, :) = w_cn*xcn;
      tmatrix(:, icn) = w_cn*mcn;
      tmatrix = [tmatrix, w_tw*mcn; w_tw*xcn, 0];
      tmatrix(end, icn) = tw2cn;
      tmatrix(icn, end) = cn2tw;
      countries{end+1} = 'TW';
    end
  
    % get default fname for the DOTS data: that is
    % ../data/dots_trade_export_2017.xls relative to location of this file
    function fname = get_default_fname()
      a = which('trade_matrix');
      fname = fullfile(fileparts(fileparts(a)),'data','dots_trade_export_2017.xls');
    end
  end
  
end
