function exercise(m)

%% Increase Global Productivity

m1 = m;
m1.gg_a = m.gg_a*1.10;

m1 = steady( ...
    m1 ...
    , "fixLevel", ["gg_a", "gg_nt", "us_pch", "ea_pch", "rw_pch"] ...
    , "blocks", false ...
);

checkSteady(m1);

table( ...
    [m, m1] ...
    , ["steadyLeveL", "compareSteadyLevel", "steadyChange", "compareSteadyChange", "form", "description"] ...
    , "writeTable", {"tables/compareSteadyExercise.xlsx", "sheet", "gg_a"} ...
); %#ok<CLARRSTR>


%% Monetary Neutrality - EA

m2 = m;
m2.ea_ss_roc_pch = m2.ea_ss_roc_pch + 0.02;

m2 = steady( ...
    m2 ...
    , "fixLevel", ["gg_a", "gg_nt", "us_pch", "ea_pch", "rw_pch"] ...
    , "blocks", false ...
);

checkSteady(m2);

table( ...
    [m, m2] ...
    , ["steadyLeveL", "compareSteadyLevel", "steadyChange", "compareSteadyChange", "form", "description"] ...
    , "writeTable", {"tables/compareSteadyExercise.xlsx", "sheet", "ea_ss_roc_pch"} ...
); %#ok<CLARRSTR>


%% Monetary Neutrality - US

m3 = m;
m3.us_ss_roc_pch = m3.us_ss_roc_pch + 0.02;

m3 = steady( ...
    m3 ...
    , "fixLevel", ["gg_a", "gg_nt", "us_pch", "ea_pch", "rw_pch"] ...
    , "blocks", false ...
);

checkSteady(m3);

table( ...
    [m, m3] ...
    , ["steadyLeveL", "compareSteadyLevel", "steadyChange", "compareSteadyChange", "form", "description"] ...
    , "writeTable", {"tables/compareSteadyExercise.xlsx", "sheet", "us_ss_roc_pch"} ...
); %#ok<CLARRSTR>



%% Discount Factor - RW

m4 = m;
m4.rw_beta = 0.97;

m4 = steady( ...
    m4 ...
    , "fixLevel", ["gg_a", "gg_nt", "us_pch", "ea_pch", "rw_pch"] ...
    , "blocks", false ...
);

checkSteady(m4);

table( ...
    [m, m4] ...
    , ["steadyLeveL", "compareSteadyLevel", "steadyChange", "compareSteadyChange", "form", "description"] ...
    , "writeTable", {"tables/compareSteadyExercise.xlsx", "sheet", "rw_beta"} ...
); %#ok<CLARRSTR>


%% Government Debt - US

m5 = m;
m5.us_ss_dg_to_ngdp = real(m5.us_ss_dg_to_ngdp) + 0.50;

m5 = steady( ...
    m5 ...
    , "fixLevel", ["gg_a", "gg_nt", "us_pch", "ea_pch", "rw_pch"] ...
    , "blocks", false ...
);

table( ...
    [m, m5] ...
    , ["steadyLeveL", "compareSteadyLevel", "steadyChange", "compareSteadyChange", "form", "description"] ...
    , "writeTable", {"tables/compareSteadyExercise.xlsx", "sheet", "us_ss_dg_to_ngdp"} ...
); %#ok<CLARRSTR>


%% Government Debt - RW

m5 = m;
m5.rw_ss_dg_to_ngdp = real(m5.rw_ss_dg_to_ngdp) + 0.50;

m5 = steady( ...
    m5 ...
    , "fixLevel", ["gg_a", "gg_nt", "rw_pch", "ea_pch", "rw_pch"] ...
    , "blocks", false ...
);

table( ...
    [m, m5] ...
    , ["steadyLeveL", "compareSteadyLevel", "steadyChange", "compareSteadyChange", "form", "description"] ...
    , "writeTable", {"tables/compareSteadyExercise.xlsx", "sheet", "rw_ss_dg_to_ngdp"} ...
); %#ok<CLARRSTR>


end%

