name: Build iris-reference pages on push to iris-toolbox

on:
  push:
    branches: ["public"]
  workflow_dispatch:


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true



jobs:
  build-and-deploy:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:

      - name: Checkout GEES
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Material
        run: pip install \
               mkdocs-material \
               mkdocs-awesome-pages-plugin

      - name: Generate pages
        run: mkdocs build

      - name: Setup pages
        uses: actions/configure-pages@v2

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
  
